# Generated by Django 4.0.4 on 2022-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0004_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='taken_date',
            field=models.DateField(null=True),
        ),
    ]
