# Generated by Django 4.0.4 on 2022-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0005_donation_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='taken_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
